<a href="https://colab.research.google.com/github/Shreyagrg888/Worksheets/blob/main/Shreya_Gurung_Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dataset = pd.read_csv('/content/drive/MyDrive/medical_students_dataset.csv')

In [ ]:
dataset.head()


Student ID   Age  Gender      Height     Weight Blood Type        BMI  \
0         1.0  18.0  Female  161.777924  72.354947          O  27.645835   
1         2.0   NaN    Male  152.069157  47.630941          B        NaN   
2         3.0  32.0  Female  182.537664  55.741083          A  16.729017   
3         NaN  30.0    Male  182.112867  63.332207          B  19.096042   
4         5.0  23.0  Female         NaN  46.234173          O        NaN   

   Temperature  Heart Rate  Blood Pressure  Cholesterol Diabetes Smoking  
0          NaN        95.0           109.0        203.0       No     NaN  
1    98.714977        93.0           104.0        163.0       No      No  
2    98.260293        76.0           130.0        216.0      Yes      No  
3    98.839605        99.0           112.0        141.0       No     Yes  
4    98.480008        95.0             NaN        231.0       No      No

In [ ]:
dataset.tail()

Student ID   Age  Gender      Height     Weight Blood Type        BMI  \
199995         NaN  24.0    Male  176.503260  95.756997          B  30.737254   
199996     99997.0  29.0  Female  163.917675  45.225194        NaN  16.831734   
199997     99998.0  34.0  Female         NaN  99.648914        NaN  33.189303   
199998     99999.0  30.0  Female  156.446944  50.142824          A  20.486823   
199999    100000.0  20.0  Female  153.927409  99.928405          O  42.175189   

        Temperature  Heart Rate  Blood Pressure  Cholesterol Diabetes Smoking  
199995    99.170685        65.0           121.0        130.0       No      No  
199996    97.865785        62.0           125.0        198.0       No     Yes  
199997    98.768210        60.0            90.0        154.0      NaN      No  
199998    98.994212        61.0           106.0        225.0       No      No  
199999    98.595817        95.0           133.0        132.0      NaN      No

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object 
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object 
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object 
 12  Smoking         180000 non-null  object 
dtypes: float64(9), object(4)
memory usage: 19.8+ MB


In [ ]:
dataset.describe()

Student ID            Age         Height         Weight  \
count  180000.000000  180000.000000  180000.000000  180000.000000   
mean    49974.042078      26.021561     174.947103      69.971585   
std     28879.641657       4.890528      14.447560      17.322574   
min         1.000000      18.000000     150.000041      40.000578   
25%     24971.750000      22.000000     162.476110      54.969838   
50%     49943.500000      26.000000     174.899914      69.979384   
75%     74986.000000      30.000000     187.464417      84.980097   
max    100000.000000      34.000000     199.998639      99.999907   

                 BMI    Temperature     Heart Rate  Blood Pressure  \
count  180000.000000  180000.000000  180000.000000   180000.000000   
mean       23.338869      98.600948      79.503767      114.558033   
std         7.033554       0.500530      11.540755       14.403353   
min        10.074837      96.397835      60.000000       90.000000   
25%        17.858396      98.264750      70.000000      102.000000   
50%        22.671401      98.599654      80.000000      115.000000   
75%        27.997487      98.940543      90.000000      127.000000   
max        44.355113     100.824857      99.000000      139.000000   

         Cholesterol  
count  180000.000000  
mean      184.486361  
std        37.559678  
min       120.000000  
25%       152.000000  
50%       184.000000  
75%       217.000000  
max       249.000000

In [ ]:
x = dataset.drop(columns=['BMI'])
y = dataset['BMI']

In [ ]:
import numpy as np

# Example: number of features d = 3
d = 3
W = np.random.randn(d, 1)  # Random initialization of weights
print(W)


[[-0.09039114]
 [ 0.67202841]
 [ 0.73287034]]


In [ ]:
# Example: number of samples n = 5
n = 5
X = np.random.randn(d, n)  # Random feature matrix of size d x n
print(X)


[[ 0.49065394  0.11025393 -0.03425535  0.20790998 -0.0889031 ]
 [-0.03159012 -0.85545478 -1.71058191  0.26111635 -1.30821728]
 [ 0.60461759  1.04089865  1.76078802  0.12313537 -1.8458923 ]]


In [ ]:
# Example: create the output vector Y with n samples
Y = np.random.randn(n, 1)  # Random target values
print(Y)


[[ 0.17792927]
 [ 0.17617883]
 [-0.15735414]
 [ 0.07572163]
 [-0.83965365]]


In [ ]:
Y_pred = np.dot(W.T, X)  # Matrix multiplication W^T X
print(Y_pred)


[[ 0.37752607  0.17798785  0.14396604  0.24692665 -2.22392285]]


In [ ]:
from sklearn.model_selection import train_test_split

# Transpose X to have the correct shape (n_samples, n_features)
X = X.T

# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Print the shapes of the resulting sets to confirm the split
print(f"Training set size: X_train: {X_train.shape}, Y_train: {Y_train.shape}")
print(f"Testing set size: X_test: {X_test.shape}, Y_test: {Y_test.shape}")

Training set size: X_train: (4, 3), Y_train: (4, 1)
Testing set size: X_test: (1, 3), Y_test: (1, 1)


In [ ]:
import numpy as np

# Define the cost function
def cost_function(X, Y, W):
    """
    Parameters:
    X: Feature Matrix (n x m)
    Y: Target Matrix (n x 1)
    W: Weight Matrix (m x 1)

    Output:
    cost: Accumulated Mean Squared Error
    """
    # Predictions from the model
    predictions = X.dot(W)  # Using matrix multiplication to calculate predictions

    # Calculate the errors (difference between predictions and actual values)
    errors = predictions - Y

    # Calculate the squared errors
    squared_errors = errors ** 2

    # Calculate the mean of squared errors (MSE)
    cost = np.mean(squared_errors)

    return cost

# Test case
X_test = np.array([[1, 2], [3, 4], [5, 6]])  # Feature matrix (3 samples, 2 features)
Y_test = np.array([3, 7, 11])  # Actual target values (3 samples)
W_test = np.array([1, 1])  # Weight matrix (2 features)

# Calculate the cost using the defined cost function
cost = cost_function(X_test, Y_test, W_test)

# Check if the cost function works as expected (for testing purposes)
if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong: Reimplement the cost function")

# Output the cost
print("Cost function output:", cost)


Proceed Further
Cost function output: 0.0


In [ ]:
import numpy as np

# Define the cost function (Mean Squared Error)
def cost_function(X, Y, W):
    predictions = X.dot(W)  # Hypothesis: X * W
    errors = predictions - Y
    squared_errors = errors ** 2
    cost = np.mean(squared_errors)
    return cost

# Gradient Descent Function
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.
    Parameters:
    X (numpy.ndarray): Feature matrix (m x n).
    Y (numpy.ndarray): Target vector (m x 1).
    W (numpy.ndarray): Initial guess for parameters (n x 1).
    alpha (float): Learning rate.
    iterations (int): Number of iterations for gradient descent.

    Returns:
    tuple: A tuple containing the final optimized parameters (W_update) and the history of cost values
    W_update (numpy.ndarray): Updated parameters (n x 1).
    cost_history (list): History of cost values over iterations.
    """
    # Initialize cost history
    cost_history = [0] * iterations
    m = len(Y)  # Number of samples

    for iteration in range(iterations):
        # Step 1: Hypothesis Values
        Y_pred = X.dot(W)  # Linear regression prediction

        # Step 2: Difference between Hypothesis and Actual Y (Error)
        loss = Y_pred - Y  # Difference between predicted and actual values

        # Step 3: Gradient Calculation
        dw = (2 / m) * X.T.dot(loss)  # Gradient of the MSE cost function

        # Step 4: Updating Values of W using Gradient
        W_update = W - alpha * dw  # Update weights using the gradient and learning rate

        # Step 5: New Cost Value
        cost = cost_function(X, Y, W_update)  # Calculate new cost
        cost_history[iteration] = cost  # Store cost in history

        # Update W for next iteration
        W = W_update

    return W_update, cost_history


# Generate random test data
np.random.seed(0)  # For reproducibility
X = np.random.rand(100, 3)  # 100 samples, 3 features
Y = np.random.rand(100)     # 100 target values
W = np.random.rand(3)       # Initial guess for parameters

# Set hyperparameters
alpha = 0.01  # Learning rate
iterations = 1000  # Number of iterations

# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)

# Print the final parameters and cost history
print("Final Parameters:", final_params)
print("Cost History:", cost_history[-10:])  # Print the last 10 cost values to show convergence


Final Parameters: [0.19444407 0.46183379 0.18966481]
Cost History: [0.10574227113217625, 0.10573999748870692, 0.10573773169129916, 0.10573547371250427, 0.10573322352497082, 0.10573098110144402, 0.10572874641476572, 0.10572651943787385, 0.10572430014380199, 0.10572208850567939]


In [ ]:
import numpy as np

# Model Evaluation - RMSE
def rmse(Y, Y_pred):
    """
    This Function calculates the Root Mean Square Error (RMSE).

    Input Arguments:
    Y: Array of actual (Target) Dependent Variables.
    Y_pred: Array of predicted Dependent Variables.

    Output Arguments:
    rmse: Root Mean Square Error.
    """
    # Calculate the squared differences between actual and predicted values
    squared_errors = (Y - Y_pred) ** 2

    # Calculate the mean of squared errors
    mean_squared_error = np.mean(squared_errors)

    # Take the square root to get RMSE
    rmse_value = np.sqrt(mean_squared_error)

    return rmse_value


# Model Evaluation - R2
def r2(Y, Y_pred):
    """
    This Function calculates the R Squared (R²) Error.

    Input Arguments:
    Y: Array of actual (Target) Dependent Variables.
    Y_pred: Array of predicted Dependent Variables.

    Output Arguments:
    r2: R Squared Error.
    """
    # Calculate the mean of actual values
    mean_y = np.mean(Y)

    # Calculate Total Sum of Squares (SS_tot)
    ss_tot = np.sum((Y - mean_y) ** 2)

    # Calculate Residual Sum of Squares (SS_res)
    ss_res = np.sum((Y - Y_pred) ** 2)

    # Calculate R Squared (R²)
    r2_value = 1 - (ss_res / ss_tot)

    return r2_value
# Test the RMSE and R2 functions with example data
Y_test = np.array([3, 7, 11])  # Actual values
Y_pred_test = np.array([2.9, 6.8, 10.9])  # Predicted values

# Calculate RMSE
rmse_value = rmse(Y_test, Y_pred_test)
print("RMSE:", rmse_value)

# Calculate R²
r2_value = r2(Y_test, Y_pred_test)
print("R²:", r2_value)


RMSE: 0.14142135623730953
R²: 0.998125


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Assuming the gradient descent, rmse, and r2 functions are already defined

# Main Function
def main():
    # Step 1: Load the dataset
    #data = pd.read_csv('student.csv')  # Use proper quotes

    # Step 2: Split the data into features (X) and target (Y)
    X = data[['Math', 'Reading']].values  # Features: Math and Reading marks
    Y = data['Writing'].values  # Target: Writing marks

    # Step 3: Split the data into training and test sets (80% train, 20% test)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # Step 4: Initialize weights (W) to zeros, learning rate, and number of iterations
    W = np.zeros(X_train.shape[1])  # Initialize weights
    alpha = 0.00001  # Learning rate
    iterations = 1000  # Number of iterations for gradient descent

    # Step 5: Perform Gradient Descent
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    # Step 6: Make predictions on the test set
    Y_pred = np.dot(X_test, W_optimal)

    # Step 7: Evaluate the model using RMSE and R-Squared
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)

    # Step 8: Output the results
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)

# Execute the main function
if __name__ == "__main__":
    main()


FileNotFoundError: [Errno 2] No such file or directory: 'student.csv'