<a href="https://colab.research.google.com/github/Shreyagrg888/Worksheet0/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#problem 1

import numpy as np
empty_array = np.empty((2,2))
print("Empty array: ")
print(empty_array)

one_array = np.ones((4,2))
print("One arrray: ")
print(one_array)

shape = (2,2)
fill_value = 9
array = np.full(shape, fill_value)
print("Filled array: ")
print(array)

given_array = np.array([[1,2],[3,4]])
zeros_array = np.zeros_like(given_array)
print("Zeros array: ")
print(zeros_array)

new_array = np.array([[1,2],[3,4]])
ones_array = np.ones_like(new_array)
print("Ones array: ")
print(ones_array)

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Numpy array: ")
print(numpy_array)

Empty array: 
[[0. 0.]
 [0. 0.]]
One arrray: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled array: 
[[9 9]
 [9 9]]
Zeros array: 
[[0 0]
 [0 0]]
Ones array: 
[[1 1]
 [1 1]]
Numpy array: 
[1 2 3 4]


In [ ]:
#Problem 2 Array manipulation

import numpy as np

array = np.arange(10,50)
print("Array ranging from 10 to 50 is: ")
print(array)

array2 = np.arange(9).reshape(3,3)
print("Matix: ")
print(array2)

array3 = np.eye(3)
print("Identity matirx: ")
print(array3)

random_array = np.random.random(30)
mean = random_array.mean()
print("Mean: ")
print(mean)

array4 = np.random.random((10,10))
minimum = array4.min()
maximum = array4.max()
print("Minimum: ")
print(minimum)
print("Maximum: ")
print(maximum)

zero_array = np.zeros(10)
zero_array[5]= 1
print("Zero Array: ")
print(zero_array)

array = [1,2,0,0,4,0]
reverse = array[::-1]
print("Reversed array: ")
print(reverse)

border_array = np.ones((6,6))
border_array[1:-1, 1:-1]= 0
print("array: ")
print(border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard: ")
print(checkerboard)




Array ranging from 10 to 50 is: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Matix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity matirx: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 
0.5271493502041833
Minimum: 
0.0025367276671033334
Maximum: 
0.998816437074205
Zero Array: 
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Reversed array: 
[0, 4, 0, 0, 2, 1]
array: 
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
Checkerboard: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#problem3
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w =  np.array([11,12])

sum = x+y
print("Sum: ")
print(sum)

subtract = w - v
print("Subtraction: ")
print(subtract)

multiply = 5*x
print("Multiplication: ")
print(multiply)

square = np.square(y)
print("Square: ")
print(square)

dotproduct_vw = np.dot(v,w)
dotproduct_xv = np.dot(x,v)
dotproduct_xy = np.dot(x,y)
print("Dotproduct of vw: ", dotproduct_vw)
print("Dotproduct of xv: ", dotproduct_xv)
print("Dotproduct of xy: ", dotproduct_xy)

xy_row = np.concatenate((x,y), axis = 0)
vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis =1)
print("Concatenation of x,y along row: ")
print(xy_row)
print("Concatenation of v,w along column: ")
print(vw_col)





Sum: 
[[ 6  8]
 [10 13]]
Subtraction: 
[2 2]
Multiplication: 
[[ 5 10]
 [15 25]]
Square: 
[[25 36]
 [49 64]]
Dotproduct of vw:  219
Dotproduct of xv:  [29 77]
Dotproduct of xy:  [[19 22]
 [50 58]]
Concatenation of x,y along row: 
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v,w along column: 
[[ 9 11]
 [10 12]]


In [ ]:
# Problem4

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(np.round(result, decimals=10))

AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)

ABT = np.transpose(AB)
print(ABT)
AT = np.transpose(A)
BT = np.transpose(B)
BTAT = np.dot(BT, AT)
print(BTAT)


A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
result = np.dot(A_inv, B)
print(result)


[[1. 0.]
 [0. 1.]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
[ 2.  1. -2.]


In [13]:
#experiment
import numpy as np
import time

# List and Numpy Array Initialization
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
np_array1 = np.arange(size)
np_array2 = np.arange(size)

# Element-wise Addition
print("Element-wise Addition:")

# Using Python Lists
start_time = time.time()
list_result_add = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_result_add = np_array1 + np_array2
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Element-wise Multiplication
print("\nElement-wise Multiplication:")

# Using Python Lists
start_time = time.time()
list_result_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_result_mul = np_array1 * np_array2
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Dot Product
print("\nDot Product:")

# Using Python Lists
start_time = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_dot_product = np.dot(np_array1, np_array2)
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")

# Matrix Multiplication
print("\nMatrix Multiplication:")
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Using Python Lists
def matrix_mult(mat1, mat2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]
    return result

start_time = time.time()
list_matrix_result = matrix_mult(list_matrix1, list_matrix2)
end_time = time.time()
print(f"Python Lists: {end_time - start_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_matrix_result = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print(f"NumPy Arrays: {end_time - start_time:.6f} seconds")



Element-wise Addition:
Python Lists: 0.167521 seconds
NumPy Arrays: 0.007639 seconds

Element-wise Multiplication:
Python Lists: 0.161260 seconds
NumPy Arrays: 0.005489 seconds

Dot Product:
Python Lists: 0.141619 seconds
NumPy Arrays: 0.002126 seconds

Matrix Multiplication:
Python Lists: 197.646466 seconds
NumPy Arrays: 3.020578 seconds
